services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.6.4
    restart: always
    ports:
      - "10100:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_BOOTSTRAP_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_BOOTSTRAP_ADMIN_PASSWORD}
      KC_HOSTNAME: ${KEYCLOAK_HOSTNAME}
      KC_DB: ${KEYCLOAK_DB_VENDOR}
      KC_DB_URL: ${KEYCLOAK_DB_URL}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USERNAME}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    volumes:
      - ./providers:/opt/keycloak/providers
    command:
      - start
      - --http-enabled=true
      - --proxy-headers=xforwarded
